### ISSUE TITLE
Cannot be installed from npm

### ISSUE THREAD

**Issue by scott-cornwell** [DanielHZhang/superbuffer#49]
I tried to use this on Stackblitz and I thought it was just their system, but I tried a plain `npm install superbuffer` locally and I just get the license and readme markdown files and the package.json. Please package so that it can be installed, I would love to use it!

**Comment by radimsv** [comment]
looks like the build has not been performed before publish :( 
That is too bad, the library looks promising
cc @DanielHZhang

**Comment by DanielHZhang** [comment]
Fixed in the new release (v1.1.1)
