### ISSUE TITLE
No packages after using pnpm install

### ISSUE THREAD

**Issue by nixjs** [DanielHZhang/superbuffer#58]
I used pnpm add superbuffer. After installing I checked node_modules and found out there is no source code, only package.json, readme.md, license.md

<img width="317" alt="image" src="https://user-images.githubusercontent.com/23132483/235812521-3c38ef4c-9bf2-40bb-912f-9a0a6436cd76.png">

**Comment by DanielHZhang** [comment]
Fixed in the new release (v1.1.1)
